### PR TITLE
Moved some icons under appshell/res/1x folder

### PR DESCRIPTION
**Pull request by ficristo**
I was a bit confused by these icons not be in a specific folder.

Side note: why only the icons with 1x resolution are mentioned in gyp?

### CODE REVIEW

**Comment by nethip** [comment]
@ficristo I am not sure if this change ever gets baked into the product. I see that we have manually added resources, on Windows, to `cefclient.rc` file.

**Comment by ficristo** [comment]
So they aren't needed to be defined on the gyp side?
I'm a bit confused how this should work...

**Comment by nethip** [comment]
I don't have a Windows machine at my Home. I will check and let you know tomorrow, when I get to the office.

**Comment by nethip** [comment]
@ficristo I was referring to this specific code. https://github.com/adobe/brackets-shell/pull/558/files#diff-a4a63dee4259dd6b62c8cccceb28a7daR194, inside `appshell.gyp`. I think they are there for reference purposes as the actual resources are defined inside `cefclient.rc`

About the change as such, I think the general convention is, if there is no scale factor appended to an image, it is considered 1x so I am not sure if want to move them under 1x folder.

**Comment by ficristo** [comment]
I still think it is a bit confusing how it is now but I'm fine to close this PR.
It is not so important.

**Comment by ficristo** [comment]
I close this stale PR.

**Pull request closed without merging**
