### PR TITLE
Added HiDPI icons for Windows.

### PR DESCRIPTION
**Pull request by larz0**
@JeffryBooher 👍

### CODE REVIEW

**Comment by pthiess** [comment]
@larz0 We need to nominate this as an item to be prioritized in the backlog -- I put it into that state in the [backlog](https://trello.com/c/WRhZ0xvj). Once @ryanstewart has prioritized it we can continue.

**Comment by MarcelGerber** [comment]
The close icons still look a little aliased.

**Comment by larz0** [comment]
@MarcelGerber could you take a screenshot of what the close icon looks like on HiDPI?

**Comment by MarcelGerber** [comment]
I don't have a HiDPI monitor here, but from what I can clearly see when looking at the icons in this PR, they are simply upscaled with no antialiasing at all.
I suppose you could see the difference.

**Comment by larz0** [comment]
@MarcelGerber ok cool. I don't think there are antialiasing on the original close icon at 1x. I'll see if I can find a surface pro 3 in the office to see if the icon is aliased or not.

**Comment by peterflynn** [comment]
@larz0 It might be less about anti-aliasing and more about just doing a vector rescale.  Right now the "X" is just rescaled with pixel doubling, so it's not taking advantage of the extra pixels at all.  An aliased but finer-grained "X" would probably look better on the high DPI screen...

**Comment by peterflynn** [comment]
@JeffryBooher Could you give an estimate of how much work would be needed to use these icons in brackets-shell?  Besides the manifest change, I assume we'd need to change a .rc file to bundle these icons and then write code to choose which icons/positioning to use depending on DPI.  How much work would all that be?

**Comment by JeffryBooher** [comment]
@peterflynn the RC change is nothing really and the Hi-DPI detection is somewhat trivial. Then it's just a day to change the code to scale those buttons based on the monitor DPI settings.  Since it can scale a percentage we would need to test a vary of ranges so another day testing.  I'd add another day just to buffer it a bit just in case something goes awry.  So about 3 days. 

The only thing that concerns me is if the app is displayed on 2 monitors with mismatched DPI settings.  I think in that case we just fallback to 100% DPI but we will need to test that case as well.

**Comment by larz0** [comment]
@peterflynn @MarcelGerber I've redrawn the close icons based on the actual HiDPI close icons.

**Comment by peterflynn** [comment]
@larz0 Sweet, those look great!

**Comment by MarcelGerber** [comment]
Yeah, that's way better.

**Comment by abose** [comment]
Thanks for uploading the PSD files. We have generated the 1.25x, 1.5x, 2x and 2.5x icons from the source and merged via pull req.502. So, closing this pull request.

**Pull request closed without merging**
