### PR TITLE
Move resource(_util*) under a new browser folder

### PR DESCRIPTION
**Pull request by ficristo**
Another cleanup to match more the cefclient.
Build on Windows 10 with VS2015u3

### CODE REVIEW

**Comment by MarcelGerber** [comment]
@ingorichter Can you try building/running this one on your Mac, too?

Btw, everything's fine here on my Windows 10 machine, VS 2012 Express.

**Comment by ingorichter** [comment]
LGTM. It's builds just fine on OSX 10.11.6 with xcode 7.3.1.

**Comment by ingorichter** [comment]
@ficristo I assume you compiled on Linux?

**Comment by ficristo** [comment]
@ingorichter unfortunately I still cannot compile master on Linux. I hope to at least get there soon.
I'm pretty sure this will work, since it is mostly a copy & paste from the cefclient example.

**Comment by MarcelGerber** [comment]
Looks good to me. Good work!

**Pull request merged**
