### PR TITLE
atom org -> electron org

### PR DESCRIPTION
**Pull request by levrik**

### CODE REVIEW

**Comment by ingorichter** [comment]
@levrik Did you sign the contributor license agreement? Otherwise we can't merge your PR. Thanks for supporting Brackets.

**Comment by levrik** [comment]
@ingorichter Do I really need this for an URL change in the README? Can you just manually commit my correction?

**Comment by nethip** [comment]
@levrik Whether the change is small or bug, we would always like to give attribution to the author of the change and also it is required by our legal.  Please sign the contributor license agreement so that you can contribute in future as well. Looking forward for some :smile:

**Comment by levrik** [comment]
@nethip Then sorry, I don't want to give my address away for a URL change in the README. I will close this.

**Pull request closed without merging**
