### PR TITLE
Fix crash on quit in CEF 2171 linux

### PR DESCRIPTION
**Pull request by jasonsanjose**
Note: This is a merge into `jasonsanjose/cef_2171_linux`

Merge work from PR #458 from @nathanial. Update code to work with linux 2171.

@nethip can you try this and see if it fixes the bug? It seems to work better for me. It only crashed on quit once after a few dozen tries where the previous code crashed pretty consistently in my VM.

### CODE REVIEW

**Comment by nethip** [comment]
@jasonsanjose I had already made the change which was done by @nathanial, but I also ran into similar conditions like what you ran into. After this change the crash occurrence has reduced but the crash is still there. One of the side effects I observed with this change was to do with process quit. Though the window closes after clicking on the close button, the process was not getting killed at all(I saw this in the system monitor). Let me know if you are seeing similar results. If not we should merge this change.

**Comment by jasonsanjose** [comment]
@nethip Hmm, for once I have good news. For me, when the window closes (either the X or File > Quit) the processes also go away. Maybe try rebuilding with this branch?

**Comment by peterflynn** [comment]
So this is needed before PR #499 can be merged?

**Comment by ficristo** [comment]
Not needed anymore. See https://github.com/adobe/brackets-shell/pull/619

**Pull request closed without merging**
