### PR TITLE
node 6.3.1 for linux

### PR DESCRIPTION
**Pull request by zaggino**
complements https://github.com/adobe/brackets-shell/pull/543

### CODE REVIEW

**Comment by zaggino** [comment]
I've tested building this on Linux, file watching works as expected.

**Comment by ficristo** [comment]
I didn't run the full test suite here. This is what I noticed so far:
- I've run all the `Unit` tests and `KeyBindingManager` has a couple of failures which I doubt is related
- I've run `Integration \ FindInFiles` test with a failure which is not related (is on master too)
- there are some problems under `LivePreview` tests
- `Extensions \ JSQuickEdit & JavaScript Code Hinting` pass

**Comment by ficristo** [comment]
@MarcelGerber could you test this too?

**Comment by MarcelGerber** [comment]
In my testing, the tests that failed were broken on `linux-1547`, too.
LGTM.

**Pull request merged**
