### PR TITLE
Update license year range to latest release

### PR DESCRIPTION
**Pull request by pra85**

### CODE REVIEW

**Comment by abose** [comment]
Thanks for contributing to brackets.
It's 2016 now.
Could you change it to something like `2012 - present`

**Comment by pra85** [comment]
@abose I have updated the pull request with the changes you suggested

**Comment by abose** [comment]
https://github.com/adobe/brackets/pull/12092 also seems related.
Could you raise a pull request changing all the licence details to this format? I know its a bit to ask of you, but that change will fix this permanently. 
You could raise the PR in stages.

**Comment by abose** [comment]
Confirmed with @ryanstewart  that the legal wording is ok to go.
LGTM merging :+1:

**Comment by abose** [comment]
Thanks @pra85 for initiating this change.

**Comment by MitchellBouwman** [comment]
Amazing job!

**Pull request merged**
