### PR TITLE
Changed launch script for bash shell to launch Brackets in a non blocking way

### PR DESCRIPTION
**Pull request by nethip**
`MING32/git bash` surprisingly understands `start` command. So changed the script to launch Brackets in non- blocking mode. However this does not work well with `CYGWIN`. So retained the earlier way of launching Brackets.exe in blocking mode in `CYGWIN`.

### CODE REVIEW

**Comment by nethip** [comment]
@rroshan1 @sprintr Could you review this PR?

**Comment by sprintr** [comment]
:cool: Works just as expected on Git bash

**Comment by nethip** [comment]
@rroshan1 I will change the name of the OF. About the ".". this usually is the case with `CYGWIN`. This was something I found in my unit tests.

**Comment by rroshan1** [comment]
Changes look good. Merging.

**Pull request merged**
