### PR TITLE
fix libgcrypt dependency on debian 8 jessie

### PR DESCRIPTION
**Pull request by jasonsanjose**
See https://github.com/adobe/brackets/issues/10255

### CODE REVIEW

**Comment by peterflynn** [comment]
@jasonsanjose Is this change only correct after Linux has switched to the new CEF?  (PR #499 hasn't been merged yet...)

**Comment by jasonsanjose** [comment]
No, this shouldn't require the new CEF. However, I'm having some trouble building with CEF 1547 when merging this PR with master, so I'm unable to confirm that at the moment.

**Comment by Romane-T** [comment]
Good morning

See also thread https://github.com/adobe/brackets/issues/10255 re: libcrypt version breaks Brackets

As per posting in that thread from Jason, installed and tested build at https://github.com/adobe/brackets/releases/download/linux-cef-2171/Brackets.Release.1.2.64-bit.deb.

Previous version of Brackets purged. libgcrypt11 purged.

Installed Brackets from above link. No errors, no warnings. Runs (so far) with no problems.

Debian Jessie with KDE as desktop environment.

With greetings

Romane

**Comment by nethip** [comment]
@jasonsanjose Do you have some cycles to validate this PR? Is this good to be merged?

**Comment by jasonsanjose** [comment]
Sorry, I don't have any spare cycles.

**Comment by ingorichter** [comment]
Let me get my vm image back to work, then I can check this out.

**Comment by brbsix** [comment]
I saw this discussed in https://github.com/adobe/brackets/issues/10255 and just want to confirm that this will not work. The *.deb* will install of course, but Brackets won't start. Even string-replacing all references to libgcrypt.so.11 with libgcrypt.so.20 in *lib/libcef.so* will not work. The current CEF has an unavoidable hard dependency on the libgcrypt11 shared library.

**Comment by nethip** [comment]
@brbsix Thanks for taking some time in testing and confirming 👍 

@ingorichter Thanks for your time too! We could definently use your expertise in this issue.

**Comment by jellemdekker** [comment]
Fixed by: [adobe/brackets-shell#619](https://github.com/adobe/brackets-shell/pull/619). This pull request is now obsolete.

**Pull request closed without merging**
