### PR TITLE
Compress .png files using Zopfli

### PR DESCRIPTION
**Pull request by MarcelGerber**
Again, compressing our `.png` files using [zopflipng](https://www.npmjs.com/package/zopflipng-bin), which is lossless compression.
Saves us 251kB.

### CODE REVIEW

**Comment by ficristo** [comment]
If we compresse the same images again what will happen? Will the images come back identical, I mean without be more compressed?

**Comment by petetnt** [comment]
@ficristo nothing would happen, just equally compressed :nail_care:

**Comment by ficristo** [comment]
In this case, merged.

**Comment by MarcelGerber** [comment]
Well, I'm not quite sure, as Zopfli in the standard configuration only tries a set amount of time (read: very often) to optimize these images. So it could be that, based on an already compressed image, it can manage to shave off a few more bits. We can also set Zopfli to run a multitude of calculations more (which can take several hours sometimes) so we can get even better results, but I'm not sure this is worth the hassle.

**Comment by ficristo** [comment]
@MarcelGerber thank you for the explanation.
No I don't want to compress at max the images, I only wanted to know what would happen.

**Pull request merged**
