### PR TITLE
Replaced util macros in favour of cef_helpers|cef_logging ones

### PR DESCRIPTION
**Pull request by ficristo**
And I removed the file since now it is unused.

### CODE REVIEW

**Comment by nethip** [comment]
Great job @ficristo 👍 Really appreciate it!

**Comment by nethip** [comment]
I tried building `remove-util` branch on MAC and I am getting this error.

screen shot 2016-06-21 at 9 05 29 pm

@ficristo Could you have a look at this error?

**Comment by ficristo** [comment]
The defines to check the OS weren't working (not on OSX).
I tryed adding the cef_build or cef_task or cef_logging headers but it causes some problems on Windows.
I've copied the code to define the OS from the cef_build header, now it should work.

**Comment by nethip** [comment]
I am able to build this now on MAC.

**Comment by nethip** [comment]
Thanks @ficristo

**Pull request merged**
