### PR TITLE
Rework a bit appshell gyp files

### PR DESCRIPTION
**Pull request by ficristo**
They match a bit more the one in the cefclient example.

### CODE REVIEW

**Comment by ficristo** [comment]
@nethip @ingorichter @abose someone of you can review? Thanks.

**Comment by MarcelGerber** [comment]
Builds and runs fine for me on Windows 10, Visual Studio 2012.

**Comment by ingorichter** [comment]
It builds and runs fine for me on OS 10.11.6 with Xcode 7.3. Tests passed.

**Comment by ficristo** [comment]
Thank you all.

**Pull request merged**
